In [24]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [26]:
df.shape

(28, 3)

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df[['age', 'affordibility']],df.bought_insurance, test_size = 0.3, random_state = 25)

In [28]:
len(x_train)

19

In [29]:
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age']/100

x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age']/100

In [30]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape = (2,), activation = 'sigmoid', kernel_initializer = 'ones', bias_initializer = 'zeros')
])

model.compile(optimizer = 'adam',
             loss = 'binary_crossentropy',
             metrics = ['accuracy'])
model.fit(x_train_scaled, y_train, epochs = 50)

D:\DeepLearning\venv\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 899ms/step - accuracy: 0.5789 - loss: 0.6482
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5789 - loss: 0.6480
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5789 - loss: 0.6477
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5789 - loss: 0.6475
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5789 - loss: 0.6472
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5789 - loss: 0.6470
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5789 - loss: 0.6467
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5789 - loss: 0.6464
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5789 - loss: 0.6462
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5789 - loss: 0.6459
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5789 - loss: 0.6457
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5789 - loss: 0.6454


In [31]:
model.evaluate(x_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.3333 - loss: 0.8259


[0.8258721232414246, 0.3333333432674408]

In [32]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step


array([[0.79403913],
       [0.7452123 ],
       [0.54942775],
       [0.76287067],
       [0.7971369 ],
       [0.8149933 ],
       [0.75237817],
       [0.5564908 ],
       [0.616464  ]], dtype=float32)

In [33]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
0     0
13    0
6     0
Name: bought_insurance, dtype: int64

In [34]:
coef, intercept = model.get_weights()
coef, intercept

(array([[0.95243984],
        [0.9510752 ]], dtype=float32),
 array([-0.04927548], dtype=float32))

In [35]:
def sigmoid(x):
    import math
    return 1/(1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [36]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

In [37]:
prediction_function(.47,1)

C:\Users\Dell\AppData\Local\Temp\ipykernel_9764\3885159617.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1 + math.exp(-x))


0.7940391092372784

In [38]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [39]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [44]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0
        
    def fit(self, x, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(x['age'], x['affordibility'], y, epochs, loss_thresold)

    def predict(self, x_test):
        weigthed_sum = self.w1*x_test['age']+self.w2*x_test['affordibility']+self.bias
        return sigmoid_numpy(weigthed_sum)

    def gradient_descent(self, age, affordibility, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
    
        for i in range(epochs):
            weighted_sum = w1 * age + w2* affordibility + bias
            y_predicted = sigmoid_numpy(weighted_sum)
    
            loss = log_loss(y_true, y_predicted)
    
    
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
            w2d = (1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))
    
            bias_d = np.mean(y_predicted-y_true)
    
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            if i%50==0:
                print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            if loss<=loss_thresold:
                print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break
    
        return w1, w2, bias

In [49]:
customModel = myNN()
customModel.fit(x_train_scaled, y_train, epochs = 5000, loss_thresold = 0.4433)

Epoch:0, w1:0.9889590343991516, w2:0.9605100280733173, bias:-0.07926911922718616, loss:0.6482464826346737
Epoch:50, w1:1.648569513567938, w2:0.995345764889503, bias:-0.9451354427468239, loss:0.5611917372000745
Epoch:100, w1:2.39104451607289, w2:1.0889211871188738, bias:-1.326573270702499, loss:0.5327623106330734
Epoch:150, w1:3.0719504952582417, w2:1.1125810233743052, bias:-1.6271016685173572, loss:0.5104777389323873
Epoch:200, w1:3.691436873278665, w2:1.1106346646465557, bias:-1.8812339449000528, loss:0.4924709416109721
Epoch:250, w1:4.253684331792159, w2:1.1004893322201528, bias:-2.104513224124534, loss:0.4777715927867156
Epoch:300, w1:4.764139762509416, w2:1.0888200362932303, bias:-2.3046660209926766, loss:0.46569664904084496
Epoch:350, w1:5.228329247573219, w2:1.0780002508029816, bias:-2.486044630125024, loss:0.45572170167967513
Epoch:400, w1:5.651385846479405, w2:1.068705580003656, bias:-2.6514549985153524, loss:0.44743630530495193
Epoch:429, w1:5.879743295855901, w2:1.06403914859

In [47]:
customModel.predict(x_test_scaled)

2     0.734542
10    0.675533
21    0.486987
11    0.696654
14    0.738350
9     0.760445
0     0.684074
13    0.494341
6     0.557841
dtype: float64

In [48]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


array([[0.79403913],
       [0.7452123 ],
       [0.54942775],
       [0.76287067],
       [0.7971369 ],
       [0.8149933 ],
       [0.75237817],
       [0.5564908 ],
       [0.616464  ]], dtype=float32)